# Generated by Django 4.0.4 on 2022-11-29 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloggingPage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogfield',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
