# Generated by Django 4.0.4 on 2022-10-11 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloggingPage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogfield',
            name='related_blog',
            field=models.ManyToManyField(blank=True, related_name='related_to', to='bloggingPage.blogfield'),
        ),
    ]
