# Generated by Django 4.0.4 on 2022-12-05 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloggingPage', '0002_alter_blogfield_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogfield',
            name='views',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
