# Generated by Django 4.0.4 on 2022-11-29 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloggingPage', '0002_alter_blogfield_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogfield',
            name='feature_article',
        ),
    ]
