# Generated by Django 4.0.4 on 2022-11-29 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloggingPage', '0003_remove_blogfield_feature_article'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogfield',
            old_name='hidepost',
            new_name='publish',
        ),
    ]
