# Generated by Django 4.0.4 on 2022-11-18 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloggingPage', '0003_alter_blogfield_related_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogfield',
            name='hidepost',
            field=models.BooleanField(default=False),
        ),
    ]
