# Generated by Django 4.0.4 on 2022-12-13 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloggingPage', '0003_alter_blogfield_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogfield',
            name='like',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
