# Generated by Django 3.2.9 on 2023-01-03 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloggingPage', '0004_blogfield_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogfield',
            name='related_blog',
            field=models.ManyToManyField(blank=True, related_name='_bloggingPage_blogfield_related_blog_+', to='bloggingPage.blogField'),
        ),
    ]
