# Generated by Django 4.0.4 on 2022-12-01 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloggingPage', '0005_remove_blogcatagory_name_blogcatagory_publish'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tags',
            old_name='name',
            new_name='title',
        ),
    ]
