"""
Django settings for thesecretvaleyjournal project.

Generated by 'django-admin startproject' using Django 3.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-kzrf0u$p7=lhj9ugq%l9byy#9h9e$pr+h9w5lvpvu36lb#xv=e'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'register',
    'bloggingPage',
    'blogingPdf',
    'homepage',
    'social_django',
    'history',
    'privacy_policy',
    'django.contrib.humanize',
    'morningNews',
    'fileshare',
]

DBBACKUP_STORAGE = 'django.core.files.storage.FileSystemStorage'
DBBACKUP_STORAGE_OPTIONS = {'location': BASE_DIR/'/backup/'}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'thesecretvaleyjournal.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'thesecretvaleyjournal.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'republicktm',
        'USER': 'postgres',
        'PASSWORD': '1532',
        'HOST': 'localhost',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# FRAOLA_EDITOR_THIRD_PARTY = ('image_aviary','spell_checker')
# FLOALA_EDITOR_PLUGINS = ('align','char_counter','code_view','colors','draggable','entities','file','font_family','font_size','fullscreen','hr_rule','image','image_manager','inline_style','line_breaker','link','lists','local_image','media','print','quick_insert','quote','save','special_characters','table','url','video','word_paste')

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/


# AUTH_USER_MODEL = 'bloggingPage.User'

# # Auth0 Settings
# SOCIAL_AUTH_TRAILING_SLASH = False
# SOCIAL_AUTH_AUTH0_DOMAIN = 'shishirbastola.us.auth0.com'
# SOCIAL_AUTH_AUTH0_KEY = 'NN0kPphOiIqG26mTlo5oNC3tREwVGUTe'
# SOCIAL_AUTH_AUTH0_SECRET = 'dv6yWYJPR5-Cy5MOFtuYMPzJvGueH6JMV1jRwD4DqRJ8eqHntvuk05GhSaC3Vyss'
# SOCIAL_AUTH_AUTH0_SCOPE = ['openid','profile','email']

# AUTHENTICATION_BACKENDS = {
#     'social_core.backends.auth0.Auth0OAuth2',
#     'django.contrib.auth.backends.ModelBackend'
# }

# LOGIN_URL = '/login/auth0'
# LOGIN_REDIRECT_URL = '/'
# LOGOUT_REDIRECT_URL = '/'


# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# set the maximum file size to 100MB (in bytes)
FILE_UPLOAD_MAX_MEMORY_SIZE = 104857600

STATIC_URL = '/static/'
MEDIA_URL = '/media/'

STATICFILES_DIRS = [
    BASE_DIR / "static",
]
STATIC_ROOT = "/static/"
# if DEBUG:
#     STATICFILES_DIRS = [os.path.join(BASE_DIR,'static')]
# else:
#     STATIC_ROOT = os.path.join(BASE_DIR, 'assets')
    
MEDIA_ROOT = os.path.join(BASE_DIR,'media')

# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'royell4912@gmail.com'
EMAIL_HOST_PASSWORD = 'dyndxfmoqiwfeaog'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
