# Generated by Django 4.0.4 on 2022-11-29 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bloggingPage', '0003_remove_blogfield_feature_article'),
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloggingPage.blogfield')),
            ],
        ),
    ]
