# Generated by Django 3.2.9 on 2023-02-18 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='headerimg',
            old_name='hide',
            new_name='published',
        ),
    ]
