# Generated by Django 4.0.4 on 2022-11-18 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='headerimg',
            name='hide',
            field=models.BooleanField(default=True),
        ),
    ]
