# Generated by Django 3.2.9 on 2023-12-20 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_rename_hide_headerimg_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='domainUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urls', models.TextField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SelectedUrls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.domainurl')),
            ],
        ),
    ]
