# Generated by Django 4.0.4 on 2022-11-18 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_headerimg_hide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headerimg',
            name='hide',
            field=models.BooleanField(default=False),
        ),
    ]
