# Generated by Django 3.2.9 on 2023-12-20 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_domainurl_selectedurls'),
    ]

    operations = [
        migrations.RenameField(
            model_name='selectedurls',
            old_name='feature_article',
            new_name='SelectedUrls',
        ),
    ]
