# Generated by Django 4.0.4 on 2022-12-06 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bloggingPage', '0003_alter_blogfield_views'),
        ('history', '0002_alter_history_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloggingPage.blogfield'),
        ),
    ]
