# Generated by Django 3.2.9 on 2023-01-31 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogingPdf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookpdf',
            name='sem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blogingPdf.sem'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='sem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blogingPdf.sem'),
        ),
    ]
