# Generated by Django 3.2.9 on 2023-02-20 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('morningNews', '0003_auto_20230220_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsdiscription',
            name='catagory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='morningNews.catagory'),
        ),
    ]
