# Generated by Django 3.2.9 on 2023-02-21 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morningNews', '0005_news_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsdiscription',
            name='heading',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
